export const SUBREDDIT_POSTS_FETCH_REQUEST = "SUBREDDIT_INFO_FETCH_REQUEST";
export const SUBREDDIT_POSTS_FETCH_FAILURE = "SUBREDDIT_INFO_FETCH_FAILURE";
export const SUBREDDIT_POSTS_FETCH_SUCCESS = "SUBREDDIT_INFO_FETCH_SUCCESS";
